name: Publish Formula

on:
  push:
    branches: [ main ]
    paths:
      - "Formula/*.rb"

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Homebrew Bundler RubyGems
        run: brew install-bundler-gems

      - name: Get changed formulas
        id: changes
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} \
            | grep '^Formula/.*\.rb$' || true)
          echo "CHANGED_FORMULAS=$CHANGED" >> $GITHUB_ENV

      - name: Audit and test changed formulas
        run: |
          for f in $CHANGED_FORMULAS; do
            echo "Processing '$f'"
            brew audit --strict "$f"
            app=$(basename "$f" .rb | tr '[:upper:]' '[:lower:]')
            echo "Installing '$app'"
            brew install "runnyc/tap/$app"
            "$app" --version
          done
