name: Publish Formula

on:
  push:
    branches: [ main ]
    paths:
      - "Formula/*.rb"

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Homebrew Bundler RubyGems
        run: brew install-bundler-gems

      - name: Get changed formulas
        id: changes
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} \
            | grep '^Formula/.*\.rb$' || true)
          echo "CHANGED_FORMULAS=$CHANGED" >> $GITHUB_ENV

      - name: Audit and test changed formulas
        run: |
          if [ -z "$CHANGED_FORMULAS" ]; then
            echo "No changed formulas detected. Exiting."
            exit 0
          fi

          echo "Changed formulas detected:"
          echo "$CHANGED_FORMULAS"

          IFS=$'\n'  # Split by newline for multiple files
          for f in $CHANGED_FORMULAS; do
            if [[ -f "$f" ]]; then
              app=$(basename "$f" .rb | tr '[:upper:]' '[:lower:]')
              echo "=== Processing '$app' ==="
              echo "Running brew audit on '$app'..."
              brew audit --strict "runnyc/tap/$app"
              echo "Installing '$app' from tap..."
              brew install "runnyc/tap/$app"
              echo "Checking '$app' version..."
              "$app" --version
              echo "=== Done with '$app' ==="
            fi
          done
          unset IFS
